###########################################
#   MofuEventAssist Configuration File!!  #
#             Author: NAFU_at             #
#            Version: 1.0                 #
###########################################

# This configuration is necessary to use this plugin.
initialization:
  #This is an SQL setting to store data for this plugin.
  database:
    type: MARIADB # MYSQL or MARIADB
    address: localhost
    port: 3306
    database: eventassist
    username: eventassist
    password: EvEnTaSsIsT
    tablePrefix: ea_

messages:
